[package]
name = "escrow_contract"
type = "contract"
authors = ["wonderland"]
compiler_version = ">=0.18.0"

[dependencies]
aztec = { git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.20.0", directory="yarn-project/aztec-nr/aztec" }
authwit = { git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.20.0", directory="yarn-project/aztec-nr/authwit" }
safe_math = { git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.20.0", directory="yarn-project/aztec-nr/safe-math" }