[package]
name = "constructor"
type = "contract"
authors = ["wonderland"]
compiler_version = ">=0.20.0"

[dependencies]
aztec = { git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.20.0", directory="yarn-project/aztec-nr/aztec" }
field_note = { git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.20.0", directory="yarn-project/aztec-nr/field-note" }